If a card could not be parsed due to missing abilities, report name of the card in the exception. Without this change you would not have known which card is unparseable.
before:
ScriptParseException: unknown ability "Menace"

after:
InvalidDeckException: Error parsing Dimir Spybug: unknown ability "Menace"